### ISSUE TITLE
Demo no longer online?

### ISSUE THREAD

**Issue by TSlivede** [cocuh/SVG-Table#20]
As the demo you linked in your readme (http://2014.typowriter.org/SVG-Table/) seems to be down, could you just enable github pages and provide a demo there?

**Comment by cocuh** [comment]
Thank you for reaching out to me. I shut down server a couple years ago, and some data is lost including the demo page. I tried to build it, but it no longer works correctly. I changed readme to make sure this library is already deprecated.
